# @name create-user
POST http://localhost:8080/users/create
Content-Type: application/json

{
  "name": "Vitor Esser",
  "username": "vitoresser",
  "password": "12345"
}

###

# @name create-task
POST http://localhost:8080/tasks/create
Content-Type: application/json
Authorization: Basic vitoresser:12345

{
  "description": "Task to add CPF field to user registration.",
  "title": "Add CPF field",
  "priority": "High",
  "startAt": "2023-10-15T15:30:00",
  "endAt": "2023-10-16T18:00:00"
}

###

###

# @name update-task
PUT http://localhost:8080/tasks/update/6bc28e11-57c2-49b7-8e81-724e37d5f928
Content-Type: application/json
Authorization: Basic vitoresser:12345

{
  "title": "Add CPF field and validation",
  "priority": "Medium"
}

###

# @name list-tasks
GET http://localhost:8080/tasks/list
Authorization: Basic vitoresser:12345

###
